# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: dotnet restore

- script: dotnet build
  displayName: dotnet build

# - script: dotnet test
  # displayName: dotnet test

# TODO: Publish test results

- script: dotnet pack
  displayName: dotnet pack

# publish build artifacts to drop folder so we can use them for release
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "build_output"
    ArtifactName: "drop"
    ArtifactType: "Container"
  displayName: Publish build artifacts
